---
# =================================================================================================
# Areas
# =================================================================================================
- name: area/docker
  color: "3970E4"
- name: area/github
  color: "000000"
- name: area/go
  color: "844FBA"
