---
extends: default

formatter:
  type: basic
  retain_line_breaks_single: true # Keeps existing newlines
  include_document_start: true
  max_line_length: 150
  scan_folded_as_literal: true # Preserves block scalars
  pad_line_comments: 1

rules:
  line_ending: lf
  trailing_spaces: trim
  end_of_file: ensure-newline
