---
version: 2
project_name: talswitcher

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    binary: "{{.ProjectName}}"
    goos:
      - linux
      - darwin
    ldflags:
      - -s -w -X github.com/mirceanton/{{.ProjectName}}/cmd.version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"

checksum:
  disable: false
  name_template: "checksum_{{.ProjectName}}_{{.Os}}_{{.Arch}}.txt"
  split: true
