---
version: 2
project_name: talswitcher

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    binary: "{{.ProjectName}}"
    goos:
      - linux
      - darwin
    ldflags:
      - -s -w -X github.com/mirceanton/{{.ProjectName}}/cmd.version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"

checksum:
  disable: false
  name_template: "checksum_{{.ProjectName}}_{{.Os}}_{{.Arch}}.txt"
  split: true

changelog:
  disable: false
  use: github
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "CI"
      regexp: ".*ci.*"
      order: 998
    - title: Others
      order: 999

nfpms:
  - homepage: https://github.com/mirceanton/{{.ProjectName}}
    maintainer: Mircea-Pavel Anton <contact@mirceanton.com>
    description: A simple tool to switch between Talos Linux contexts.
    file_name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"
    license: MIT
    formats: [deb, apk, rpm]
