---
# yaml-language-server: $schema=https://json.schemastore.org/semantic-release.json
branches:
  - master
  - main

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
