---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

env:
  VERSION:
    sh: git describe --tags --always --dirty
  DIR_NAME:
    sh: basename $(git rev-parse --show-toplevel)

tasks:
  build:
    desc: Run goreleaser in snapshot mode.
    cmd: goreleaser release --snapshot --clean

  test:
    desc: Run tests.
    cmd: go test -v ./... -race -covermode=atomic

  lint:
    desc: Run linter.
    cmd: golangci-lint run --fix
