---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Actionlint
permissions: { contents: read }

on:
  workflow_dispatch: {}
  push:
    paths:
      - ".github/workflows/*.yaml"
      - ".mise.toml"

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup mise
        uses: jdx/mise-action@156251fcc627ac4e26cb0f93dd47d1d4979abf24 # v3.3.0

      - name: Run actionlint
        run: mise exec -- actionlint
