---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Actionlint
permissions: { contents: read }

on:
  workflow_dispatch: {}
  push:
    paths:
      - ".github/workflows/*.yaml"
      - ".mise.toml"

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup mise
        uses: jdx/mise-action@eb2f5cb41b0a8175dad2f797e3daca6fe7795a19 # v2.4.2

      - name: Run actionlint
        run: mise exec -- actionlint
