---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Actionlint
permissions: { contents: read }

on:
  workflow_dispatch: {}
  push:
    paths:
      - ".github/workflows/*.yaml"
      - ".mise.toml"

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup mise
        uses: jdx/mise-action@e3d7b8d67a7958d1207f6ed871e83b1ea780e7b0 # v3.3.1

      - name: Run actionlint
        run: mise exec -- actionlint
