---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Commitlint
permissions: { contents: read }

on:
  pull_request_target: {}
  push: {}

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup mise
        uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2.4.4

      - name: Validate PR Title
        if: github.event_name == 'pull_request_target'
        run: echo "$PR_TITLE" | mise exec -- commitlint --verbose
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}

      - name: Validate last commit
        if: github.event_name == 'push'
        run: mise exec -- commitlint --last --verbose
