---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Commitlint
permissions: { contents: read }

on:
  pull_request_target: {}
  push: {}

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup mise
        uses: jdx/mise-action@156251fcc627ac4e26cb0f93dd47d1d4979abf24 # v3.3.0

      - name: Validate PR Title
        if: github.event_name == 'pull_request_target'
        run: echo "$PR_TITLE" | mise exec -- commitlint --verbose
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}

      - name: Validate last commit
        if: github.event_name == 'push'
        run: mise exec -- commitlint --last --verbose
