---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: DevContainer Docker Build

on:
  workflow_dispatch: {}

  pull_request:
    paths:
      - ".github/workflows/devcontainer-build.yaml"
      - ".devcontainer/Dockerfile"

jobs:
  release:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-docker-build-push.yaml@40a5d6ce235ca5631b31b0677258950a35f94a24 # v3.5.0
    secrets: inherit
    with:
      image: "ghcr.io/${{ github.repository }}-devcontainer"
      platforms: linux/amd64
      tags: test
      context: ./.devcontainer
      dockerfile: ./.devcontainer/Dockerfile
      dry-run: true
