---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: DevContainer Docker Build

on:
  workflow_dispatch: {}

  pull_request:
    paths:
      - ".github/workflows/devcontainer-build.yaml"
      - ".devcontainer/Dockerfile"

jobs:
  release:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-docker-build-push.yaml@e3a95ef75601e0b811d0e3f1b9afc04a175acb22 # v3.6.0
    secrets: inherit
    with:
      image: "ghcr.io/${{ github.repository }}-devcontainer"
      platforms: linux/amd64
      tags: test
      context: ./.devcontainer
      dockerfile: ./.devcontainer/Dockerfile
      dry-run: true
