---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: DevContainer Docker Build

on:
  workflow_dispatch: {}

  pull_request:
    paths:
      - ".github/workflows/devcontainer-build.yaml"
      - ".devcontainer/Dockerfile"

jobs:
  release:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-docker-build-push.yaml@fe8cb068ccf362fa75af3e2336fb24e1b04c5ccf # v3.4.15
    secrets: inherit
    with:
      image: "ghcr.io/${{ github.repository }}-devcontainer"
      platforms: linux/amd64
      tags: test
      context: ./.devcontainer
      dockerfile: ./.devcontainer/Dockerfile
      dry-run: true
