---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: DevContainer Docker Build

on:
  workflow_dispatch: {}

  pull_request:
    paths:
      - ".github/workflows/devcontainer-build.yaml"
      - ".devcontainer/Dockerfile"

jobs:
  release:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-docker-build-push.yaml@240678cf33f0c0c65f0323615c925f0312b2d640 # v3.4.27
    secrets: inherit
    with:
      image: "ghcr.io/${{ github.repository }}-devcontainer"
      platforms: linux/amd64
      tags: test
      context: ./.devcontainer
      dockerfile: ./.devcontainer/Dockerfile
      dry-run: true
