---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Docker Release

on:
  workflow_dispatch:
    inputs:
      custom-tag:
        type: string
        description: Additional custom tags for the image.
        required: false
  pull_request:
    paths:
      - "*.go"
      - "go.mod"
      - "go.sum"
  push:
    tags: ["*"]

jobs:
  release:
    uses: mirceanton/reusable-workflows/.github/workflows/docker-release.yaml@main
    secrets: inherit
    with:
      image-name: ghcr.io/${{ github.repository }}
      custom-tag: ${{ inputs.custom-tag }}
      platforms: linux/amd64, linux/arm64
      build-args: |
        VERSION=${{ inputs.custom-tag || github.ref_name }}
