---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Git Release

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Dry run"
        required: false
        default: false
        type: boolean

  pull_request:
    paths:
      - ".github/workflows/git-release.yaml"
      - "cmd/**"
      - "go.mod"
      - "go.sum"
      - "main.go"

  push:
    branches: ["main"]
    paths:
      - "cmd/**"
      - "go.mod"
      - "go.sum"
      - "main.go"

jobs:
  release:
    uses: mirceanton/reusable-workflows/.github/workflows/git-release-semver.yaml@5420663687d3db97f9f4bc50854259e1ce3b38f6
    secrets: inherit
    with:
      dry-run: ${{ inputs.dry-run || github.event_name == 'pull_request' }}
