---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Git Release

on:
  workflow_dispatch: {}
  push:
    branches: ["main"]
    paths:
      - "cmd/**"
      - "go.mod"
      - "go.sum"
      - "main.go"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@3378cda945da322a8db4b193e19d46352ebe2de5 # v1.10.4
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Set up Node.js
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install semantic-release @semantic-release/github

      - name: Run semantic-release
        run: |
          npx semantic-release \
            --branches=main \
            --plugins=@semantic-release/commit-analyzer \
            --plugins=@semantic-release/release-notes-generator \
            --plugins=@semantic-release/github
        env:
          GITHUB_TOKEN: "${{ steps.app-token.outputs.token }}"
