---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Git Release

on:
  # Manual Trigger
  workflow_dispatch:
    inputs:
      dry-run:
        description: Dry Run
        required: false
        default: false
        type: boolean

  # Dry Run on any PR that changes this pipeline or that should ultimately trigger a release when merged
  pull_request:
    paths:
      - ".github/workflows/git-release.yaml"
      - "go.mod"
      - "go.sum"
      - "**/**.go"

  # "Wet" Run on any push to the main branch that modified a go-related file
  push:
    branches: ["main", "master"]
    paths:
      - "go.mod"
      - "go.sum"
      - "**/**.go"

jobs:
  release:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-release-semver.yaml@e21f792b9f18066d0248ac2c9008a73a23fb84c6 # v3.4.10
    secrets: inherit
    with:
      dry-run: ${{ inputs.dry-run || github.event_name == 'pull_request' }}
