---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Golang CI

on:
  workflow_dispatch: {} # Manual Trigger
  pull_request:
    paths:
      - "*.go"
      - "go.mod"
      - "go.sum"

jobs:
  release:
    uses: mirceanton/reusable-workflows/.github/workflows/go-ci.yaml@main
    secrets: inherit
