---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Go Lint

on:
  workflow_dispatch: {}

  pull_request:
    paths:
      - ".github/workflows/go-lint.yaml"
      - ".golangci.yaml"
      - "go.mod"
      - "go.sum"
      - "cmd/**"

jobs:
  golangci-lint:
    uses: mirceanton/reusable-workflows/.github/workflows/go-lint.yaml@5420663687d3db97f9f4bc50854259e1ce3b38f6
    secrets: inherit
    with:
      go-version: "1.22.5"
      golangci-version: "v1.60.3"
