---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Go Lint

on:
  workflow_dispatch: {}

  pull_request:
    paths:
      - ".github/workflows/go-lint.yaml"
      - ".golangci.yaml"
      - "go.mod"
      - "go.sum"
      - "cmd/**"

jobs:
  golangci-lint:
    uses: mirceanton/reusable-workflows/.github/workflows/go-lint.yaml@17d8ef4df857d93b905170956fbbcd56b296e8bb
    secrets: inherit
    with:
      # renovate: datasource=golang-version depName=go
      go-version: "1.22.0"

      # renovate: datasource=docker depName=golangci/golangci-lint
      golangci-version: "v1.60.0"
