---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Go Release

on:
  workflow_dispatch: {}

  push:
    tags: ["*"]

  pull_request:
    paths:
      - ".github/workflows/go-release.yaml"
      - "*.go"
      - "go.mod"
      - "go.sum"

jobs:
  release:
    uses: mirceanton/reusable-workflows/.github/workflows/go-release.yaml@main
    secrets: inherit
