---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Go Release

on:
  workflow_dispatch: {}

  push:
    tags: ["*"]

  pull_request:
    paths:
      - ".github/workflows/go-release.yaml"
      - ".goreleaser.yaml"
      - "go.mod"
      - "go.sum"
      - "cmd/**"

jobs:
  goreleaser:
    uses: mirceanton/reusable-workflows/.github/workflows/go-release.yaml@17d8ef4df857d93b905170956fbbcd56b296e8bb
    secrets: inherit
    with:
      dry-run: ${{ inputs.dry-run || github.event_name == 'pull_request' }}

      # renovate: datasource=golang-version depName=go
      go-version: "1.22.0"

      # renovate: datasource=docker depName=goreleaser/goreleaser
      goreleaser-version: "v2.1.0"
