---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Goreleaser

on:
  # Manual Trigger
  workflow_dispatch:
    inputs:
      dry-run:
        description: Dry Run
        required: false
        default: false
        type: boolean

  # Dry Run on any PR that changes this pipeline or that should ultimately trigger a release when merged
  pull_request:
    paths:
      - ".github/workflows/goreleaser.yaml"
      - "go.mod"
      - "go.sum"
      - "**/**.go"

  # "Wet" Run on any tag push
  push:
    tags: ["*"]

jobs:
  goreleaser:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-go-release.yaml@d11c71dd28b7392383e908f9d68379c7f075e716 # v3.4.32
    secrets: inherit
    with:
      dry-run: ${{ inputs.dry-run || github.event_name == 'pull_request' }}
