---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Goreleaser
permissions: { contents: read }

on:
  release: { types: [published] } # wet run
  push: # dry run
    paths:
      - .github/workflows/goreleaser.yaml
      - .goreleaser.yaml
      - ".mise.toml"
      - "**.go"
      - "go.mod"
      - "go.sum"
  workflow_dispatch:
    inputs:
      dry-run:
        description: Dry Run
        required: false
        default: false
        type: boolean

jobs:
  goreleaser:
    if: github.repository_owner == 'mirceanton' # ? don't run on forks -> missing repo secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with: { fetch-depth: 0 }

      - name: Setup mise
        uses: jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566 # v3.2.0

      - name: Run goreleaser (dry-run)
        if: github.event_name != 'release' || inputs.dry-run == 'true'
        run: goreleaser --snapshot
        env: { TAP_GITHUB_TOKEN: "${{ secrets.GHCR_RW_TOKEN }}" }

      - name: Generate Token
        if: github.event_name == 'release' || inputs.dry-run == 'false'
        uses: actions/create-github-app-token@def152b8a737443d7af6c5722c6389146fe90c90 # v2.1.2
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Login to Container Registry
        if: github.event_name == 'release' || inputs.dry-run == 'false'
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          registry: "ghcr.io"
          username: "${{ github.actor }}"
          password: "${{ secrets.GHCR_RW_TOKEN }}"

      - name: Run goreleaser
        if: github.event_name == 'release' || inputs.dry-run == 'false'
        run: mise exec -- goreleaser --clean
        env:
          GITHUB_TOKEN: "${{ steps.app-token.outputs.token }}"
          TAP_GITHUB_TOKEN: "${{ secrets.GHCR_RW_TOKEN }}"
