---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Label Sync

on:
  # Manual Trigger
  workflow_dispatch:
    inputs:
      dry-run:
        description: Dry Run
        default: true
        required: false
        type: boolean

  # Dry Run on any PR that changes the labels config or the workflow
  pull_request:
    paths:
      - .github/workflows/label-sync.yaml
      - .github/labels.yaml

  # "Wet" Run on any push to the main branch that changes the labels config or the workflow
  push:
    branches: ["main", "master"]
    paths:
      - .github/workflows/label-sync.yaml
      - .github/labels.yaml

  # "Wet" Run daily hourly
  schedule:
    - cron: "0 * * * *"

jobs:
  label-sync:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-label-sync.yaml@e21f792b9f18066d0248ac2c9008a73a23fb84c6 # v3.4.10
    secrets: inherit
    with:
      dry-run: ${{ inputs.dry-run || github.event_name == 'pull_request' }}
      config-file: .github/labels.yaml
