---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Labeler

on:
  pull_request_target: {}

jobs:
  pr-labeler:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-labeler.yaml@e21f792b9f18066d0248ac2c9008a73a23fb84c6 # v3.4.10
    secrets: inherit
    with:
      config-file: .github/labeler.yaml
