---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Labeler

on:
  pull_request_target: {}

jobs:
  pr-labeler:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-labeler.yaml@0597f9bbb74266a6163f20579f414733e5f52870 # v3.4.13
    secrets: inherit
    with:
      config-file: .github/labeler.yaml
