---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Labeler

on:
  pull_request_target: {}

jobs:
  pr-labeler:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-labeler.yaml@v3.8.0
    secrets: inherit
    with:
      config-file: .github/configs/labeler.yaml
