---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Labeler

on:
  pull_request_target: {}

jobs:
  pr-labeler:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-labeler.yaml@2a155b83746904fc3d6e784663ef7e94ceca11f8 # v3.4.23
    secrets: inherit
    with:
      config-file: .github/labeler.yaml
