---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Labeler

on:
  pull_request_target: {}

jobs:
  pr-labeler:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-labeler.yaml@40a5d6ce235ca5631b31b0677258950a35f94a24 # v3.5.0
    secrets: inherit
    with:
      config-file: .github/labeler.yaml
