---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Labeler

on:
  pull_request_target: {}

jobs:
  pr-labeler:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-labeler.yaml@03898112670be8cb0d0f94d80b3c3aa6dbdc12d7 # v3.4.43
    secrets: inherit
    with:
      config-file: .github/labeler.yaml
