---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Labeler

on:
  pull_request_target: {}

jobs:
  pr-labeler:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-labeler.yaml@f3ac2fda0bc700f58df88287fde0d40df7d39b7d # v3.4.31
    secrets: inherit
    with:
      config-file: .github/labeler.yaml
