---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Labeler

on:
  pull_request_target: {}

jobs:
  pr-labeler:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-labeler.yaml@9fc3a5514908a2e37215948be2dda45c876c603f # v3.4.30
    secrets: inherit
    with:
      config-file: .github/labeler.yaml
