---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Labeler

on:
  pull_request_target: {}

jobs:
  pr-labeler:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-labeler.yaml@2981539811fdf240b8f704ced3e88b0ef4e4f326 # v3.4.7
    secrets: inherit
    with:
      config-file: .github/labeler.yaml
