---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Labeler

on:
  pull_request_target: {}

jobs:
  pr-labeler:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-labeler.yaml@45c10dd21623ccf437b9b1b7d5137b96dae54f54 # v3.4.47
    secrets: inherit
    with:
      config-file: .github/labeler.yaml
