---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Labeler

on:
  pull_request_target: {}

jobs:
  pr-labeler:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-labeler.yaml@d11c71dd28b7392383e908f9d68379c7f075e716 # v3.4.32
    secrets: inherit
    with:
      config-file: .github/labeler.yaml
