---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Labeler

on:
  pull_request_target: {}

jobs:
  pr-labeler:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-labeler.yaml@f5d2be58302e684938588ae00c6d4006f650a739 # v3.4.38
    secrets: inherit
    with:
      config-file: .github/labeler.yaml
