---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Labeler

on:
  pull_request_target: {}

jobs:
  pr-labeler:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-labeler.yaml@81cb89e04633886fc057e412e2f171c686b27a9a # v3.4.33
    secrets: inherit
    with:
      config-file: .github/labeler.yaml
