---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Labeler

on:
  pull_request_target: {}

jobs:
  pr-labeler:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-labeler.yaml@155cb0eb3f146478d30884e385490eb28ce6fd7c # v3.4.21
    secrets: inherit
    with:
      config-file: .github/labeler.yaml
