---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Labeler

on:
  pull_request_target: {}

jobs:
  pr-labeler:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-labeler.yaml@fe8cb068ccf362fa75af3e2336fb24e1b04c5ccf # v3.4.15
    secrets: inherit
    with:
      config-file: .github/labeler.yaml
