---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Labeler

on:
  pull_request_target: {}

jobs:
  pr-labeler:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-labeler.yaml@eb91426a79e7b63c4649650b2aaa80c11d966ee8 # v3.4.24
    secrets: inherit
    with:
      config-file: .github/labeler.yaml
