---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Labeler

on:
  pull_request_target: {}

jobs:
  pr-labeler:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-labeler.yaml@71c748260211464d1d58c43d7fb019f7adac19b3 # v3.5.1
    secrets: inherit
    with:
      config-file: .github/labeler.yaml
