---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Labeler

on:
  pull_request_target: {}

jobs:
  pr-labeler:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-labeler.yaml@e3a95ef75601e0b811d0e3f1b9afc04a175acb22 # v3.6.0
    secrets: inherit
    with:
      config-file: .github/labeler.yaml
