---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Labeler

on:
  pull_request_target: {}

jobs:
  pr-labeler:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-labeler.yaml@5a742438be20864a4bf11eb158cc402cf970dd79 # v3.4.6
    secrets: inherit
    with:
      config-file: .github/labeler.yaml
