---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Labeler

on:
  pull_request_target: {}

jobs:
  pr-labeler:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-labeler.yaml@e923b666f157f12715483c3fd0e0d466d9af9325 # v3.4.39
    secrets: inherit
    with:
      config-file: .github/labeler.yaml
