---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Labeler

on:
  pull_request_target: {}

jobs:
  pr-labeler:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-labeler.yaml@a61b1e9d0db0bbf13227375edd00d7041ff50a70 # v3.4.29
    secrets: inherit
    with:
      config-file: .github/labeler.yaml
