---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Labeler

on:
  pull_request_target: {}

jobs:
  pr-labeler:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-labeler.yaml@b32156dbd9442d9e9a80a24b7b25f0d97b6dcb52 # v3.4.22
    secrets: inherit
    with:
      config-file: .github/labeler.yaml
