---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Labeler

on:
  pull_request_target: {}

jobs:
  pr-labeler:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-labeler.yaml@2866305533698de1309183d4e6031425a83ce350 # v3.4.52
    secrets: inherit
    with:
      config-file: .github/labeler.yaml
