---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Labeler

on:
  pull_request_target: {}

jobs:
  pr-labeler:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-labeler.yaml@9ce913356128f964413b5fe99efe4858e18d7831 # v3.4.51
    secrets: inherit
    with:
      config-file: .github/labeler.yaml
