---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Labeler

on:
  pull_request_target: {}

jobs:
  pr-labeler:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-labeler.yaml@9c446d05d840db108ef8fcf0bb0f67f5049ed9b0 # v3.4.40
    secrets: inherit
    with:
      config-file: .github/labeler.yaml
