---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Labeler

on:
  pull_request_target: {}

jobs:
  pr-labeler:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-labeler.yaml@e4d5023d61f4f79f382a457eaff9700730421553 # v3.4.45
    secrets: inherit
    with:
      config-file: .github/labeler.yaml
