---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Labeler

on:
  pull_request_target: {}

jobs:
  pr-labeler:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-labeler.yaml@4de40c2d203237c9f76d8dd17f1887f027341d04 # v3.4.25
    secrets: inherit
    with:
      config-file: .github/labeler.yaml
