---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Labeler

on:
  pull_request_target: {}

jobs:
  pr-labeler:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-labeler.yaml@173cc64a72c4859559203ad5a335cf1afb111bb7 # v3.4.42
    secrets: inherit
    with:
      config-file: .github/labeler.yaml
