---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Labeler

on:
  pull_request_target: {}

jobs:
  pr-labeler:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-labeler.yaml@74f44ae21b3822cb2dec326c489ad63b1325574e # v3.4.34
    secrets: inherit
    with:
      config-file: .github/labeler.yaml
