---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Labeler

on:
  pull_request_target: {}

jobs:
  pr-labeler:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-labeler.yaml@2dc165dbaca3733e48c4951e080807c372b64fd8 # v3.4.11
    secrets: inherit
    with:
      config-file: .github/labeler.yaml
