---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release
permissions: { contents: read }

on:
  schedule: [{ cron: '0 0 * * *' }]
  push: {}
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Dry run mode (no actual release)'
        required: false
        default: true
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  release:
    if: github.repository_owner == 'mirceanton' # ? don't run on forks
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@0f859bf9e69e887678d5bbfbee594437cb440ffe # v2.1.0
        id: app-token
        with:
          app-id: '${{ secrets.BOT_APP_ID }}'
          private-key: '${{ secrets.BOT_APP_PRIVATE_KEY }}'

      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          fetch-depth: 0
          token: '${{ steps.app-token.outputs.token }}'

      - name: Release
        uses: mirceanton/action-semver-release@be5a9413659737e968dffd82b6a0a47805ffd026 # v2.0.0
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          dry-run: |
            ${{ 
              ( github.event.inputs.dry-run == 'true' && github.event_name == 'workflow_dispatch' ) ||
              github.event_name == 'push'
            }}
