---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release
permissions: { contents: read }

on:
  schedule: [{cron: '0 0 * * *'}] # wet run
  push: {} # dry run
  workflow_dispatch:
    inputs:
      version-increment:
        description: 'Version increment type'
        required: false
        default: 'auto'
        type: choice
        options: [ "auto", "major", "minor", "patch", "prerelease" ]
      dry-run:
        description: 'Dry run mode (no actual release)'
        required: false
        default: false
        type: boolean
      draft:
        description: Mark Release as Draft
        default: false
        required: false
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  release:
    if: github.repository_owner == 'mirceanton' # ? don't run on forks
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: "${{ steps.app-token.outputs.token }}"
          fetch-depth: 0  # !important for SVU to determine the next version number

      - name: Generate Release Metadata
        id: release-metadata
        uses: mirceanton/action-semver-metadata@830294a0f6ab7d2fd11067085a8732ce6066f466 # v1.0.3
        with:
          github-token: ${{ steps.app-token.outputs.token }}

      - name: Create Release
        if: ${{ (github.event_name == 'workflow_dispatch' && inputs.dry-run == 'false' ) || (github.event_name == 'schedule') }}
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # v2.3.2
        with:
          name: 'v${{ steps.release-metadata.outputs.next-version }}'
          tag_name: 'v${{ steps.release-metadata.outputs.next-version }}'
          body: ${{ steps.release-metadata.outputs.release-notes }}
          token: ${{ steps.app-token.outputs.token }}
