---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Renovate
permissions: { contents: read }

on:
  schedule: [{ cron: '0 * * * *' }]
  workflow_dispatch:
    inputs:
      dry-run:
        description: Dry Run
        default: false
        required: false
        type: boolean
      log-level:
        description: Log Level
        type: choice
        default: debug
        options: [debug, info]
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Generate Token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        id: app-token
        with:
          app-id: '${{ secrets.BOT_APP_ID }}'
          private-key: '${{ secrets.BOT_APP_PRIVATE_KEY }}'

      - name: Run Renovate
        uses: renovatebot/github-action@13da59cf7cfbd3bfea72ce26752ed22edf747ce9 # v43.0.2
        env:
          LOG_LEVEL: "${{ inputs.log-level || 'debug' }}"
          RENOVATE_AUTODISCOVER: true
          RENOVATE_AUTODISCOVER_FILTER: '${{ github.repository }}'
          RENOVATE_DRY_RUN: '${{ inputs.dry-run == true }}'
        with:
          token: '${{ steps.app-token.outputs.token }}'
