---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Renovate
permissions: { contents: read }

on:
  schedule: [{ cron: "0 * * * *" }]
  workflow_dispatch:
    inputs:
      dry-run:
        description: Dry Run
        default: false
        required: false
        type: boolean
      log-level:
        description: Log Level
        type: choice
        default: debug
        options: [ debug, info ]
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup mise
        uses: jdx/mise-action@5cb1df66ed5e1fb3c670ea0b62fd17a76979826a # v2.3.1

      - name: Generate Token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Run Renovate
        run: mise exec -- renovate
        env:
          # https://docs.renovatebot.com/self-hosted-configuration/
          LOG_LEVEL: "${{ inputs.log-level || 'debug' }}"
          RENOVATE_CONFIG_FILE: .renovaterc.json
          RENOVATE_AUTODISCOVER: true
          RENOVATE_AUTODISCOVER_FILTER: "${{ github.repository }}"
          RENOVATE_DRY_RUN: "${{ inputs.dry-run == true }}"
          RENOVATE_TOKEN: "${{ steps.app-token.outputs.token }}"
