---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Renovate
permissions: { contents: read }

on:
  schedule: [{ cron: '0 * * * *' }]
  workflow_dispatch:
    inputs:
      dry-run:
        description: Dry Run
        default: false
        required: false
        type: boolean
      log-level:
        description: Log Level
        type: choice
        default: debug
        options: [debug, info]
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Generate Token
        uses: actions/create-github-app-token@a8d616148505b5069dccd32f177bb87d7f39123b # v2.1.1
        id: app-token
        with:
          app-id: '${{ secrets.BOT_APP_ID }}'
          private-key: '${{ secrets.BOT_APP_PRIVATE_KEY }}'

      - name: Run Renovate
        uses: renovatebot/github-action@7876d7a812254599d262d62b6b2c2706018258a2 # v43.0.10
        env:
          LOG_LEVEL: "${{ inputs.log-level || 'debug' }}"
          RENOVATE_AUTODISCOVER: true
          RENOVATE_AUTODISCOVER_FILTER: '${{ github.repository }}'
          RENOVATE_DRY_RUN: '${{ inputs.dry-run == true }}'
        with:
          token: '${{ steps.app-token.outputs.token }}'
