---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Test Go

on:
  # Manual Trigger
  workflow_dispatch: {}

  # Run on any PR
  pull_request: {}

jobs:
  test:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-go-test.yaml@e7fc0b68ce5b8bf0f4c85d53928f91af6ec54357 # v3.4.36
    secrets: inherit
    with:
      go-version: stable
