---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Test Go

on:
  # Manual Trigger
  workflow_dispatch: {}

  # Run on any PR
  pull_request: {}

jobs:
  test:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-go-test.yaml@245e890bcb13f9fff4582065e849a9d01d3b63e0 # v3.4.44
    secrets: inherit
    with:
      go-version: stable
