---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Test Go

on:
  # Manual Trigger
  workflow_dispatch: {}

  # Run on any PR
  pull_request: {}

jobs:
  test:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-go-test.yaml@9ce913356128f964413b5fe99efe4858e18d7831 # v3.4.51
    secrets: inherit
    with:
      go-version: stable
