---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Test Go

on:
  # Manual Trigger
  workflow_dispatch: {}

  # Run on any PR
  pull_request: {}

jobs:
  test:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-go-test.yaml@f5d2be58302e684938588ae00c6d4006f650a739 # v3.4.38
    secrets: inherit
    with:
      go-version: stable
