---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Test Go

on:
  # Manual Trigger
  workflow_dispatch: {}

  # Run on any PR
  pull_request: {}

jobs:
  test:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-go-test.yaml@40a5d6ce235ca5631b31b0677258950a35f94a24 # v3.5.0
    secrets: inherit
    with:
      go-version: stable
