---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Test Go

on:
  # Manual Trigger
  workflow_dispatch: {}

  # Run on any PR
  pull_request: {}

jobs:
  test:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-go-test.yaml@f8a15cef06b25b9ba5fe77ffcf4f4f2810adf1c5 # v3.4.20
    secrets: inherit
    with:
      go-version: stable
