---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Trivy

permissions:
  security-events: write
  contents: read

on:
  schedule: [{cron: "1 0 * * *"}]
  pull_request: {}
  workflow_dispatch:
    inputs:
      dry-run:
        description: Dry Run
        required: false
        default: false
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Create directory for scan results
        run: mkdir -p trivy-results

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@dc5a429b52fcf669ce959baa2c2dd26090d2a6c4 # 0.32.0
        with:
          image-ref: ghcr.io/${{ github.repository }}:latest
          format: 'sarif'
          output: 'trivy-results/results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'
          ignore-unfixed: false
          vuln-type: 'os,library'

      - name: Upload Trivy scan results to GitHub Security tab
        if: ${{ !(inputs.dry-run || github.event_name == 'pull_request') }}
        uses: github/codeql-action/upload-sarif@51f77329afa6477de8c49fc9c7046c15b9a4e79d # v3.29.7
        with:
          sarif_file: 'trivy-results/results.sarif'
          category: 'trivy'
